/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    posts: Post;
    'travel-plans': TravelPlan;
    'travel-memories': TravelMemory;
    'travel-route-identities': TravelRouteIdentity;
    'timeline-events': TimelineEvent;
    'bucket-items': BucketItem;
    'wrapped-snapshots': WrappedSnapshot;
    comments: Comment;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'travel-plans': {
      memories: 'travel-memories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'travel-plans': TravelPlansSelect<false> | TravelPlansSelect<true>;
    'travel-memories': TravelMemoriesSelect<false> | TravelMemoriesSelect<true>;
    'travel-route-identities': TravelRouteIdentitiesSelect<false> | TravelRouteIdentitiesSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    'bucket-items': BucketItemsSelect<false> | BucketItemsSelect<true>;
    'wrapped-snapshots': WrappedSnapshotsSelect<false> | WrappedSnapshotsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh-TW' | 'en') | ('zh-TW' | 'en')[];
  globals: {
    'site-config': SiteConfig;
    'home-config': HomeConfig;
  };
  globalsSelect: {
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    'home-config': HomeConfigSelect<false> | HomeConfigSelect<true>;
  };
  locale: 'zh-TW' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'family';
  displayName: string;
  slug: string;
  familyRole: 'father' | 'mother' | 'daughter' | 'son' | 'grandmother' | 'family';
  profileVisibility: 'public' | 'family';
  avatar?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  cardImage?: (number | null) | Media;
  galleryImages?: (number | Media)[] | null;
  resumeMilestoneImages?: (number | Media)[] | null;
  /**
   * Controls the public footer contact block on this member profile.
   */
  publicContact?: {
    siteTitle?: string | null;
    description?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  theme: {
    persona: 'neutral' | 'tavis' | 'lynn' | 'leo' | 'academy' | 'heritage';
    primaryColor?: string | null;
    accentColor?: string | null;
  };
  status?: string | null;
  typewriter?: {
    prefix?: string | null;
    rotatingWords?:
      | {
          word: string;
          id?: string | null;
        }[]
      | null;
    suffix?: string | null;
  };
  bio?: string | null;
  beliefs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  interests?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        school: string;
        degree?: string | null;
        major?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  careerTimeline?:
    | {
        organization: string;
        role: string;
        location?: string | null;
        start?: string | null;
        end?: string | null;
        summary?: string | null;
        /**
         * Optional media shown for this career milestone. Leave empty to show no milestone media.
         */
        milestoneMedia?: (number | Media)[] | null;
        highlights?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Intro copy shown beside the Professional Timeline heading on the public member profile.
   */
  professionalTimelineIntro?: string | null;
  skillRadar?:
    | {
        skill: string;
        score: number;
        evidence?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Matches a file under content-source/profiles for future seed import.
   */
  sourceDocIdentifier?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  type: 'photo' | 'video';
  youtubeUrl?: string | null;
  altText: string;
  /**
   * Relative content-source path used only for idempotent seed imports. Admin users can replace the uploaded file later.
   */
  sourcePath?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedMembers?: (number | User)[] | null;
  relatedTravelRecord?:
    | ({
        relationTo: 'travel-plans';
        value: number | TravelPlan;
      } | null)
    | ({
        relationTo: 'travel-memories';
        value: number | TravelMemory;
      } | null);
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Planning workspaces. The end date controls Active Plans versus Archived Plans in the lobby.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-plans".
 */
export interface TravelPlan {
  id: number;
  title: string;
  /**
   * Canonical travel identity. It must not collide with a slug in the other travel collection.
   */
  slug: string;
  isPrivate?: boolean | null;
  startDate: string;
  /**
   * The lobby derives Active Plans or Archived Plans from this date.
   */
  endDate: string;
  summary?: string | null;
  coverImage?: (number | null) | Media;
  members?: (number | User)[] | null;
  guestParticipants?:
    | {
        name: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  planningSections?:
    | {
        level: number;
        title: string;
        /**
         * Stable section identity used by reconciliation and deep links.
         */
        anchor: string;
        displayDay?: string | null;
        displayDate?: string | null;
        displaySubtitle?: string | null;
        body: string;
        links?:
          | {
              label?: string | null;
              url: string;
              id?: string | null;
            }[]
          | null;
        mediaItems?: (number | Media)[] | null;
        interactions?: {
          commentsEnabled?: boolean | null;
          thumbsUpEnabled?: boolean | null;
          thumbsDownEnabled?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Virtual reverse link; the relationship is stored only on the memory.
   */
  memories?: {
    docs?: (number | TravelMemory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Seed reconciliation metadata. Managed by the travel seed workflow; editors should not change it manually.
   */
  sourceMetadata?: {
    sourceFile?: string | null;
    sourceHash?: string | null;
    parserVersion?: string | null;
    lastImportedAt?: string | null;
    /**
     * Last accepted seed projection used as Base for three-way reconciliation.
     */
    baseProjection?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Post-travel records, stories, photos, and sharing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-memories".
 */
export interface TravelMemory {
  id: number;
  title: string;
  /**
   * Canonical travel identity. It must not collide with a slug in the other travel collection.
   */
  slug: string;
  isPrivate?: boolean | null;
  startDate: string;
  endDate: string;
  summary?: string | null;
  coverImage?: (number | null) | Media;
  participants?: (number | User)[] | null;
  guestParticipants?:
    | {
        name: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional provenance link. Creating a memory never changes or removes its source plan.
   */
  originPlan?: (number | null) | TravelPlan;
  galleryImages?: (number | Media)[] | null;
  itineraryImages?: (number | Media)[] | null;
  dailyHighlights?:
    | {
        day?: number | null;
        date?: string | null;
        dateLabel?: string | null;
        title: string;
        theme?: string | null;
        story?: string | null;
        segments?:
          | {
              time?: string | null;
              activity: string;
              transport?: string | null;
              notes?: string | null;
              id?: string | null;
            }[]
          | null;
        meals?: {
          breakfast?: string | null;
          lunch?: string | null;
          dinner?: string | null;
        };
        lodging?: string | null;
        mediaItems?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  travelLedger?: {
    flights?:
      | {
          date?: string | null;
          dateLabel?: string | null;
          airline?: string | null;
          flightNumber?: string | null;
          route?: string | null;
          passengers?: string | null;
          departureTime?: string | null;
          arrivalTime?: string | null;
          terminal?: string | null;
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
    lodgings?:
      | {
          startDate?: string | null;
          endDate?: string | null;
          dateRange?: string | null;
          hotel: string;
          city?: string | null;
          address?: string | null;
          roomType?: string | null;
          bookingChannel?: string | null;
          price?: string | null;
          highlights?: string | null;
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  storySections?:
    | {
        level: number;
        title: string;
        anchor: string;
        displayDay?: string | null;
        displayDate?: string | null;
        displaySubtitle?: string | null;
        body: string;
        links?:
          | {
              label?: string | null;
              url: string;
              id?: string | null;
            }[]
          | null;
        mediaItems?: (number | Media)[] | null;
        interactions?: {
          commentsEnabled?: boolean | null;
          thumbsUpEnabled?: boolean | null;
          thumbsDownEnabled?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  externalVideos?:
    | {
        title?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  reminders?:
    | {
        category: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Seed reconciliation metadata. Managed by the travel seed workflow; editors should not change it manually.
   */
  sourceMetadata?: {
    sourceFile?: string | null;
    sourceHash?: string | null;
    parserVersion?: string | null;
    lastImportedAt?: string | null;
    /**
     * Last accepted seed projection used as Base for three-way reconciliation.
     */
    baseProjection?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  author: number | User;
  categories?: (number | Category)[] | null;
  isPrivate?: boolean | null;
  publishedDate: string;
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal registry enforcing one canonical route owner across travel collections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-route-identities".
 */
export interface TravelRouteIdentity {
  id: number;
  slug: string;
  ownerKey: string;
  owner:
    | {
        relationTo: 'travel-plans';
        value: number | TravelPlan;
      }
    | {
        relationTo: 'travel-memories';
        value: number | TravelMemory;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  title: string;
  slug: string;
  eventDate: string;
  year: number;
  summary?: string | null;
  description?: string | null;
  images?: (number | Media)[] | null;
  relatedTravelRecord?:
    | ({
        relationTo: 'travel-plans';
        value: number | TravelPlan;
      } | null)
    | ({
        relationTo: 'travel-memories';
        value: number | TravelMemory;
      } | null);
  relatedPost?: (number | null) | Post;
  relatedMembers?: (number | User)[] | null;
  sourceType: 'manual' | 'bucket-item' | 'travel' | 'post';
  isPrivate?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bucket-items".
 */
export interface BucketItem {
  id: number;
  title: string;
  description?: string | null;
  status: 'pool' | 'in-progress' | 'completed';
  priority?: number | null;
  createdBy?: (number | null) | User;
  completedBy?: (number | null) | User;
  completedAt?: string | null;
  targetDate?: string | null;
  coverImage?: (number | null) | Media;
  isPrivate?: boolean | null;
  timelineEvent?: (number | null) | TimelineEvent;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wrapped-snapshots".
 */
export interface WrappedSnapshot {
  id: number;
  year: number;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  heroMedia?: (number | null) | Media;
  summary?: string | null;
  stats?:
    | {
        label: string;
        value: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  blocks?:
    | {
        kind: 'memory' | 'travel' | 'blog' | 'wish';
        title: string;
        body?: string | null;
        accent?: string | null;
        id?: string | null;
      }[]
    | null;
  isPrivate?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  user: number | User;
  associatedType: 'travel' | 'timeline' | 'blog';
  associatedId: string;
  commentText?: string | null;
  reaction?: ('none' | 'up' | 'down' | 'heart' | 'cool' | 'applause') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'travel-plans';
        value: number | TravelPlan;
      } | null)
    | ({
        relationTo: 'travel-memories';
        value: number | TravelMemory;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'bucket-items';
        value: number | BucketItem;
      } | null)
    | ({
        relationTo: 'wrapped-snapshots';
        value: number | WrappedSnapshot;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  displayName?: T;
  slug?: T;
  familyRole?: T;
  profileVisibility?: T;
  avatar?: T;
  heroImage?: T;
  cardImage?: T;
  galleryImages?: T;
  resumeMilestoneImages?: T;
  publicContact?:
    | T
    | {
        siteTitle?: T;
        description?: T;
        email?: T;
        phone?: T;
      };
  theme?:
    | T
    | {
        persona?: T;
        primaryColor?: T;
        accentColor?: T;
      };
  status?: T;
  typewriter?:
    | T
    | {
        prefix?: T;
        rotatingWords?:
          | T
          | {
              word?: T;
              id?: T;
            };
        suffix?: T;
      };
  bio?: T;
  beliefs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  interests?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  education?:
    | T
    | {
        school?: T;
        degree?: T;
        major?: T;
        year?: T;
        id?: T;
      };
  careerTimeline?:
    | T
    | {
        organization?: T;
        role?: T;
        location?: T;
        start?: T;
        end?: T;
        summary?: T;
        milestoneMedia?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  professionalTimelineIntro?: T;
  skillRadar?:
    | T
    | {
        skill?: T;
        score?: T;
        evidence?: T;
        id?: T;
      };
  sourceDocIdentifier?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  categories?: T;
  isPrivate?: T;
  publishedDate?: T;
  coverImage?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-plans_select".
 */
export interface TravelPlansSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isPrivate?: T;
  startDate?: T;
  endDate?: T;
  summary?: T;
  coverImage?: T;
  members?: T;
  guestParticipants?:
    | T
    | {
        name?: T;
        note?: T;
        id?: T;
      };
  planningSections?:
    | T
    | {
        level?: T;
        title?: T;
        anchor?: T;
        displayDay?: T;
        displayDate?: T;
        displaySubtitle?: T;
        body?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        mediaItems?: T;
        interactions?:
          | T
          | {
              commentsEnabled?: T;
              thumbsUpEnabled?: T;
              thumbsDownEnabled?: T;
            };
        id?: T;
      };
  memories?: T;
  sourceMetadata?:
    | T
    | {
        sourceFile?: T;
        sourceHash?: T;
        parserVersion?: T;
        lastImportedAt?: T;
        baseProjection?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-memories_select".
 */
export interface TravelMemoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isPrivate?: T;
  startDate?: T;
  endDate?: T;
  summary?: T;
  coverImage?: T;
  participants?: T;
  guestParticipants?:
    | T
    | {
        name?: T;
        note?: T;
        id?: T;
      };
  originPlan?: T;
  galleryImages?: T;
  itineraryImages?: T;
  dailyHighlights?:
    | T
    | {
        day?: T;
        date?: T;
        dateLabel?: T;
        title?: T;
        theme?: T;
        story?: T;
        segments?:
          | T
          | {
              time?: T;
              activity?: T;
              transport?: T;
              notes?: T;
              id?: T;
            };
        meals?:
          | T
          | {
              breakfast?: T;
              lunch?: T;
              dinner?: T;
            };
        lodging?: T;
        mediaItems?: T;
        id?: T;
      };
  travelLedger?:
    | T
    | {
        flights?:
          | T
          | {
              date?: T;
              dateLabel?: T;
              airline?: T;
              flightNumber?: T;
              route?: T;
              passengers?: T;
              departureTime?: T;
              arrivalTime?: T;
              terminal?: T;
              notes?: T;
              id?: T;
            };
        lodgings?:
          | T
          | {
              startDate?: T;
              endDate?: T;
              dateRange?: T;
              hotel?: T;
              city?: T;
              address?: T;
              roomType?: T;
              bookingChannel?: T;
              price?: T;
              highlights?: T;
              notes?: T;
              id?: T;
            };
      };
  storySections?:
    | T
    | {
        level?: T;
        title?: T;
        anchor?: T;
        displayDay?: T;
        displayDate?: T;
        displaySubtitle?: T;
        body?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        mediaItems?: T;
        interactions?:
          | T
          | {
              commentsEnabled?: T;
              thumbsUpEnabled?: T;
              thumbsDownEnabled?: T;
            };
        id?: T;
      };
  externalVideos?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  reminders?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  sourceMetadata?:
    | T
    | {
        sourceFile?: T;
        sourceHash?: T;
        parserVersion?: T;
        lastImportedAt?: T;
        baseProjection?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-route-identities_select".
 */
export interface TravelRouteIdentitiesSelect<T extends boolean = true> {
  slug?: T;
  ownerKey?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eventDate?: T;
  year?: T;
  summary?: T;
  description?: T;
  images?: T;
  relatedTravelRecord?: T;
  relatedPost?: T;
  relatedMembers?: T;
  sourceType?: T;
  isPrivate?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bucket-items_select".
 */
export interface BucketItemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  status?: T;
  priority?: T;
  createdBy?: T;
  completedBy?: T;
  completedAt?: T;
  targetDate?: T;
  coverImage?: T;
  isPrivate?: T;
  timelineEvent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wrapped-snapshots_select".
 */
export interface WrappedSnapshotsSelect<T extends boolean = true> {
  year?: T;
  status?: T;
  publishedAt?: T;
  heroMedia?: T;
  summary?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        note?: T;
        id?: T;
      };
  blocks?:
    | T
    | {
        kind?: T;
        title?: T;
        body?: T;
        accent?: T;
        id?: T;
      };
  isPrivate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  user?: T;
  associatedType?: T;
  associatedId?: T;
  commentText?: T;
  reaction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  type?: T;
  youtubeUrl?: T;
  altText?: T;
  sourcePath?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedMembers?: T;
  relatedTravelRecord?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  contactAddress?: string | null;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'youtube' | 'instagram' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-config".
 */
export interface HomeConfig {
  id: number;
  heroTitle: string;
  heroSubtitle?: string | null;
  heroBackground?: (number | null) | Media;
  featuredTravelRecord?:
    | ({
        relationTo: 'travel-plans';
        value: number | TravelPlan;
      } | null)
    | ({
        relationTo: 'travel-memories';
        value: number | TravelMemory;
      } | null);
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactPhone?: T;
  contactEmail?: T;
  contactAddress?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-config_select".
 */
export interface HomeConfigSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroBackground?: T;
  featuredTravelRecord?: T;
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}